# Generated by Django 5.1.5 on 2025-01-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_id',
            new_name='student_ids',
        ),
    ]
