# Generated by Django 5.1.5 on 2025-01-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0002_rename_student_id_students_student_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_ids',
            new_name='student_id',
        ),
    ]
