# Generated by Django 5.1.5 on 2025-02-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0003_rename_student_ids_students_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
