# Generated by Django 5.1.5 on 2025-02-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0004_students_dob_students_email_students_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
