# Generated by Django 5.1.5 on 2025-02-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0005_students_deleted_at'),
    ]

    operations = [
    ]
