# Generated by Django 5.1.5 on 2025-02-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0006_auto_20250204_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
