# Generated by Django 5.1.5 on 2025-02-04 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentpanel', '0007_delete_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('program', models.CharField(max_length=100, blank=True, null=True)),
                ('zoho_crm_id', models.CharField(max_length=100, unique=True)),
                ('student_consent', models.IntegerField(null=True)),
                ('interview_start_at', models.DateTimeField(null=True)),
                ('answers_scores', models.IntegerField(null=True)),
                ('sentiment_score', models.IntegerField(null=True)),
                ('recording_file', models.TextField(null=True)),
                ('interview_end_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'indexes': [models.Index(fields=['id'], name='studentpane_id_593b17_idx')],
            },
        ),
    ]
