# Generated by Django 5.1.5 on 2025-02-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='zoho_crm_id',
            new_name='zoho_lead_id',
        ),
    ]
