# Generated by Django 5.1.5 on 2025-02-07 12:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0008_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interview_link', models.URLField(blank=True)),
                ('video_response', models.FileField(blank=True, null=True, upload_to='interviews/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(null=True)),
                ('ai_scores', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpanel.students')),
            ],
            options={
                'verbose_name': 'Student_Interview',
                'verbose_name_plural': 'Student_Interview',
                'indexes': [models.Index(fields=['id'], name='studentpane_id_f0ffe9_idx')],
            },
        ),
    ]
