# Generated by Django 5.1.5 on 2025-02-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0009_rename_zoho_crm_id_students_zoho_lead_id'),
        ('studentpanel', '0009_student_interview'),
    ]

    operations = [
    ]
