# Generated by Django 5.1.5 on 2025-02-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0011_students_institute_id_delete_student_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='institute_id',
        ),
    ]
