# Generated by Django 5.1.5 on 2025-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0012_remove_students_institute_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='edu_doc_verification_status',
            field=models.CharField(choices=[('unapproved', 'Unapproved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unapproved', max_length=20),
        ),
    ]
