# Generated by Django 5.1.5 on 2025-02-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0013_students_edu_doc_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='edu_doc_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='Unverified', max_length=20),
        ),
    ]
