# Generated by Django 5.1.5 on 2025-02-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0014_alter_students_edu_doc_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_interview_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
