# Generated by Django 5.1.5 on 2025-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0015_students_is_interview_link_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='interview_link_send_count',
            field=models.IntegerField(default=0),
        ),
    ]
