# Generated by Django 5.1.5 on 2025-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0016_students_interview_link_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='intake_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='intake_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
