# Generated by Django 5.1.5 on 2025-02-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0010_merge_20250212_1645'),
        ('studentpanel', '0016_students_interview_link_send_count'),
    ]

    operations = [
    ]
