# Generated by Django 5.1.5 on 2025-02-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0017_merge_20250217_1640'),
        ('studentpanel', '0017_students_intake_month_students_intake_year'),
    ]

    operations = [
    ]
