# Generated by Django 5.1.5 on 2025-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0018_merge_20250224_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_manager_email',
            field=models.EmailField(max_length=225, null=True),
        ),
    ]
