# Generated by Django 5.1.5 on 2025-02-26 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0019_students_student_manager_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInterviewAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, null=True, unique=True)),
                ('zoho_lead_id', models.CharField(max_length=100, unique=True)),
                ('question_id', models.IntegerField(null=True)),
                ('answer_text', models.TextField(null=True)),
                ('sentiment_score', models.IntegerField(null=True)),
                ('grammar_accuracy', models.TextField(null=True)),
                ('interview_end_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentInterviewAnswers',
                'verbose_name_plural': 'StudentInterviewAnswers',
                'indexes': [models.Index(fields=['id'], name='studentpane_id_ad12b2_idx')],
            },
        ),
    ]
