# Generated by Django 5.1.5 on 2025-02-26 12:50

import studentpanel.models.interview_link
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0019_students_student_manager_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInterviewLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_lead_id', models.CharField(help_text='Unique identifier from Zoho CRM', max_length=255)),
                ('interview_link', models.URLField(help_text='Interview link for the student')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the link was generated')),
                ('expires_at', models.DateTimeField(default=studentpanel.models.interview_link.default_expiry, help_text='Expiration timestamp (48 hours after creation)')),
                ('interview_attend', models.BooleanField(default=False, help_text='Indicates if the student attended the interview')),
                ('is_expired', models.BooleanField(default=False, help_text='Marks whether the link is expired')),
            ],
        ),
    ]
