# Generated by Django 5.1.5 on 2025-02-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0020_studentinterviewanswers'),
        ('studentpanel', '0020_studentinterviewlink'),
    ]

    operations = [
    ]
