# Generated by Django 5.1.5 on 2025-02-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0021_merge_20250227_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='crm_id',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
