# Generated by Django 5.1.5 on 2025-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0022_students_crm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterviewanswers',
            name='sent_subj',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentinterviewanswers',
            name='sentiment_score',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentinterviewanswers',
            name='interview_end_at',
            field=models.DateTimeField(null=True),
        ),
    ]
