# Generated by Django 5.1.5 on 2025-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0022_students_crm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bunny_stream_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
