# Generated by Django 5.1.5 on 2025-02-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0023_remove_studentinterviewanswers_sent_subj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinterviewanswers',
            name='student_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinterviewanswers',
            name='zoho_lead_id',
            field=models.CharField(max_length=100),
        ),
    ]
