# Generated by Django 5.1.5 on 2025-03-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0023_students_bunny_stream_video_id'),
        ('studentpanel', '0024_alter_studentinterviewanswers_student_id_and_more'),
    ]

    operations = [
    ]
