# Generated by Django 4.2.19 on 2025-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0025_merge_20250303_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
