# Generated by Django 4.2.19 on 2025-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0026_studentinterviewlink_interview_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterviewanswers',
            name='confidence_level',
            field=models.TextField(null=True),
        ),
    ]
