# Generated by Django 4.2.19 on 2025-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0026_alter_students_student_id'),
        ('studentpanel', '0027_studentinterviewanswers_confidence_level'),
    ]

    operations = [
    ]
