# Generated by Django 4.2.19 on 2025-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0028_merge_20250304_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterviewanswers',
            name='video_path',
            field=models.TextField(null=True),
        ),
    ]
