# Generated by Django 4.2.19 on 2025-03-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0029_studentinterviewanswers_video_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinterviewlink',
            name='total_grammer_scores',
        ),
        migrations.AddField(
            model_name='studentinterviewlink',
            name='total_grammar_scores',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentinterviewlink',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentinterviewlink',
            name='total_answer_scores',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentinterviewlink',
            name='total_sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
