# Generated by Django 4.2.19 on 2025-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0031_students_mindee_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mindee_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='', max_length=20),
        ),
    ]
