# Generated by Django 4.2.19 on 2025-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0032_alter_students_mindee_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='verification_failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
