# Generated by Django 4.2.19 on 2025-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0033_students_verification_failed_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mindee_verification_status',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
