# Generated by Django 4.2.19 on 2025-06-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0034_alter_students_mindee_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterviewlink',
            name='interview_link_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
