# Generated by Django 4.2.19 on 2025-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0035_studentinterviewlink_interview_link_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='interview_process',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
