# Generated by Django 4.2.19 on 2025-06-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0037_student_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_interview',
            name='student_id',
        ),
    ]
