# Generated by Django 4.2.19 on 2025-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0038_remove_student_interview_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterviewlink',
            name='assigned_question_ids',
            field=models.CharField(blank=True, help_text='Comma-separated IDs of assigned CommonQuestion rows', max_length=255, null=True),
        ),
    ]
