# Generated by Django 4.2.19 on 2025-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0040_studentinterviewlink_transcript_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_interview',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
