# Generated by Django 4.2.19 on 2025-07-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0041_student_interview_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterviewlink',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
