# Generated by Django 5.1.5 on 2025-01-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_rename_adminpanel__institu_996c08_idx_adminpanel__institu_1176d7_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='adminpanel__institu_996c08_idx',
            old_name='adminpanel__institu_1176d7_idx',
        ),
    ]
