# Generated by Django 5.1.5 on 2025-01-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_adminpanel__institu_1176d7_idx_adminpanel__institu_996c08_idx'),
    ]

    operations = [
    ]
