# Generated by Django 5.1.5 on 2025-01-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20250124_1245'),
    ]

    operations = [
    ]
