# Generated by Django 5.1.5 on 2025-01-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_rename_course_names_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course_names',
        ),
    ]
