# Generated by Django 5.1.5 on 2025-01-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_rename_course_name_course_course_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_names',
            new_name='course_name',
        ),
    ]
