# Generated by Django 5.1.5 on 2025-02-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_rename_course_names_course_course_name'),
        ('adminpanel', '0011_students'),
    ]

    operations = [
    ]
