# Generated by Django 5.1.5 on 2025-02-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_merge_20250205_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
