# Generated by Django 5.1.5 on 2025-02-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_merge_20250201_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
