# Generated by Django 5.1.5 on 2025-02-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_merge_20250201_1647'),
        ('adminpanel', '0013_delete_students'),
    ]

    operations = [
    ]
