# Generated by Django 5.1.5 on 2025-02-24 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_merge_0012_merge_20250201_1647_0013_delete_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='adminpanel__institu_996c08_idx',
        ),
        migrations.RemoveIndex(
            model_name='institute',
            name='adminpanel__institu_bdd489_idx',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='institute_id',
            new_name='crm_id',
        ),
        migrations.RenameField(
            model_name='institute',
            old_name='institute_id',
            new_name='crm_id',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['crm_id'], name='adminpanel__crm_id__363dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['crm_id'], name='adminpanel__crm_id_3a8143_idx'),
        ),
    ]
