# Generated by Django 5.1.5 on 2025-02-24 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_studentmanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentmanager',
            name='adminpanel__crm_id__7a434e_idx',
        ),
        migrations.RenameField(
            model_name='studentmanager',
            old_name='crm_id',
            new_name='institute_id',
        ),
        migrations.AddIndex(
            model_name='studentmanager',
            index=models.Index(fields=['institute_id'], name='adminpanel__institu_b4c5b2_idx'),
        ),
    ]
