# Generated by Django 5.1.5 on 2025-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_remove_studentmanager_adminpanel__crm_id__7a434e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmanager',
            options={'verbose_name': 'StudentManager', 'verbose_name_plural': 'StudentManager'},
        ),
    ]
