# Generated by Django 5.1.5 on 2025-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_studentmanagerprofile_delete_studentmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='crm_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
