# Generated by Django 5.1.5 on 2025-02-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_alter_institute_crm_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'crm_id')},
        ),
    ]
