# Generated by Django 5.1.5 on 2025-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_alter_course_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonquestion',
            name='answer',
        ),
        migrations.AlterField(
            model_name='commonquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
