# Generated by Django 5.1.5 on 2025-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_remove_commonquestion_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True, unique=True),
        ),
    ]
