# Generated by Django 5.1.5 on 2025-02-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_remove_question_answer_alter_question_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'course_id')},
        ),
    ]
