# Generated by Django 5.1.5 on 2025-03-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonquestion',
            name='crm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commonQuestion', to='adminpanel.institute'),
        ),
    ]
