# Generated by Django 4.2.19 on 2025-03-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_commonquestion_crm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonquestion',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
