# Generated by Django 4.2.19 on 2025-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_alter_commonquestion_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonquestion',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
