# Generated by Django 4.2.19 on 2025-03-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_alter_commonquestion_question_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('course_id',)},
        ),
    ]
