# Generated by Django 4.2.19 on 2025-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_alter_question_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
