# Generated by Django 4.2.19 on 2025-04-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
