"""
Django settings for ascencia_interviews project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import pymysql
import os

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xm5c1eakitra$psy4$sy-8o$9la=(r9kr+a&t9msif%smg4l#u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "adminpanel",
    "studentpanel",
    "studentmanagerpanel",
    'api',
    'rest_framework',
    'corsheaders',
    'sslserver',
    'django_extensions',
    'commands',
    'django_q',
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'adminpanel.middlewares.loginRequiredMiddleware.LoginRequiredMiddleware',
    'adminpanel.middlewares.Force404Middleware.Force404Middleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'ascencia_interviews.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [BASE_DIR / "templates"],
        "DIRS": [os.path.join(BASE_DIR, "frontend", "build")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'ascencia_interviews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ascencia-interviews',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',  # Or your MySQL server address
#         'PORT': '3306',       # Default MySQL port
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ascencia-interviews',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',  # Or your MySQL server address
#         'PORT': '3306',       # Default MySQL port
#     }
# }


# live
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ascenciaintervie_db',
        'USER': 'ascenciaintervie_db',
        'PASSWORD': '}Qc,O3Sw-?).',
        'HOST': '127.0.0.1',  # Or your MySQL server address
        'PORT': '3306',       # Default MySQL port
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Malta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"


STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "frontend", "build", "static"),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
STUDENT_UPLOAD = BASE_DIR 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login'


# CORS_ALLOW_ALL_ORIGINS = True
# CSRF_COOKIE_SECURE = False
# SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS
# SESSION_COOKIE_SECURE = True  # Ensure cookies are sent over HTTPS
# CSRF_COOKIE_SECURE = True  # Ensure CSRF cookies are sent over HTTPS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# CORS_ALLOWED_ORIGINS = [
#     'https://192.168.0.160:3000',  # React app URL
# ]

# # HTTP Strict Transport Security (HSTS) settings
# SECURE_HSTS_SECONDS = 31536000         # Enforce HTTPS for 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True    # Apply to all subdomains
# SECURE_HSTS_PRELOAD = True               # Allow your domain to be included in browsers’ HSTS preload list

# # Additional security settings (optional but recommended)
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True

# TESSERACT_CMD = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

# ADMIN_BASE_URL = "https://bb91-103-71-112-194.ngrok-free.app"

ADMIN_BASE_URL = "https://ascencia-interview.com"

# BUNNY_STREAM_API_KEY = "e31364b4-b2f4-4221-aac3bd5d34e5-6769-4f29"  # Replace with your actual Library Key
# BUNNY_STREAM_LIBRARY_ID = "390607"

BUNNY_STREAM_API_KEY = "9fcda8b3-9fb5-40a2-90287e129dc8-4ea3-4fd8"  # Replace with your actual Library Key
BUNNY_STREAM_LIBRARY_ID = "454645"

# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587 
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "ankita@angel-portal.com"
EMAIL_HOST_PASSWORD = "hztmgxknumenllhp"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER






# Q_CLUSTER = {
#     "name": "DjangoQCluster",
#     "workers": 8,  # Number of worker processes
#     "timeout": 90,  # Task timeout in seconds
#     "retry": 120,  # Retry failed tasks after 2 minutes
#     "queue_limit": 150,  # Maximum number of queued tasks
#     "bulk": 4,  # Number of tasks processed at once
#     "orm": "default",  # Use Django ORM for task management
# }

Q_CLUSTER = {
    "name": "DjangoQCluster",
    "workers": 6,  # Slightly fewer workers to avoid overwhelming the system
    "timeout": 3600,  # Adjusted timeout to 15 minutes (matches your task duration)
    "retry": 900,  # Retry failed tasks after 15 minutes (gives time to resolve issues)
    "queue_limit": 200,  # Increased queue size to handle more tasks
    "bulk": 10,  # Processes 3 tasks at a time for balanced load
    "orm": "default",  # Use Django ORM for task management
}


CSRF_TRUSTED_ORIGINS = [
    "https://ascencia-interview.com",
    "https://bb91-103-71-112-194.ngrok-free.app",
]

CSRF_COOKIE_SECURE = True 
CSRF_COOKIE_SAMESITE = 'None'